version: '3.8'
services:
  geolocator:
    build: .
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db:5432/geolocator"
      SECRET_KEY_BASE: "ZKLhSGa0hGdIK3Zyb/FhjEIJJPltd2kunECzk+JlU0pyczP5RY4E0r2H4tKtnGqv"
  db:
    image: postgres:16-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geolocator
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db:
    driver: local
